package br.com.cursojavanow.printxmascard.nihongo;

import br.com.cursojavanow.printxmascard.CompareAnswerBRToJP;
import br.com.cursojavanow.printxmascard.CompareAnswerJPToBR;

/**
 *
 * @author zigui
 */
public class NewJFrame extends javax.swing.JFrame {

    String sentenceBackup;
    int language = 2;

    /*
    1. traduzir do japonês
    2. escrever em japonês
     */
    public NewJFrame() {
        initComponents();
        // JTFAsk.setText("えっ!");
        //JTFAsk.setText("eh!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTFAnswer = new javax.swing.JTextField();
        JTFAsk = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        JTFAnswer.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        JTFAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFAnswerKeyReleased(evt);
            }
        });

        JTFAsk.setEditable(false);
        JTFAsk.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N

        jButton1.setText("Próximo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTFAsk)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(JTFAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 405, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTFAsk, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JTFAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFAnswerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFAnswerKeyReleased
        if (language == 1) {
            japaneseToPortuguese(evt);
        } else {
            writingJapanese(evt);
        }
    }//GEN-LAST:event_JTFAnswerKeyReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

//        Webservice webservice = new Webservice();
//        JapaneseWord japaneseWord = webservice.teste(1, 1);
//        JTFAsk.setText(japaneseWord.getWord());
    }//GEN-LAST:event_jButton1ActionPerformed

    public void japaneseToPortuguese(java.awt.event.KeyEvent evt) {
        switch (evt.getKeyCode()) {
            case 8://backspace
                backspace();
                break;
            default:
                CompareAnswerJPToBR.japaneseToPortuguese(evt, JTFAsk, JTFAnswer);
                break;
        }
    }

    public void writingJapanese(java.awt.event.KeyEvent evt) {
        System.out.println("press " + evt.getKeyCode());
        String answer = null;
        switch (evt.getKeyCode()) {
            case 8://backspace
                backspace();
                break;
            case 17: //alt
            case 18: //alt 
                System.out.println("não faça nada");
                break;
            case 78: //n 
                answer = WorkingWord.checkTheLastThreeLetters(JTFAnswer
                        .getText());
                JTFAnswer.setText(answer);
                break;
            default:
                answer = WorkingWord.checkTheLastTwoSyllables(JTFAnswer
                        .getText());
                JTFAnswer.setText(answer);
        }
    }

    public void backspace() {
        String setenceJapanese = JTFAnswer.getText();
        JTFAnswer.setText(setenceJapanese);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFAnswer;
    private javax.swing.JTextField JTFAsk;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
